config/routes.rb
Nametag::Application.routes.draw do

  match "domains/" => "domains#index", :via => [:get, :post]

  resources :domains
  resources :users

  match "/users/follow" => "users#follow", :via => :post
  match "/domains/follow" => "domains#follow", :via => :post 

  match "signup/" => "accounts#signup", :via => :get, :as => "signup"
  match "signup/" => "accounts#signup", :via => :post, :as => "signup"
  match "signin/" => "accounts#signin", :via => :get, :as => "signin"
  match "signin/" => "accounts#signin", :via => :post, :as => "signin"
  match "signout/" => "accounts#signout", :via => :get, :as => "signout"
  

  root :to => 'welcome#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/domain.rb
class Domain < ActiveRecord::Base
  attr_accessible :name, :user_id, :public, :confirmed, :for_sell, :price
  belongs_to :user
  has_many :followers, :class_name => 'DomainFollower', :foreign_key => "follower"

end

app/models/domain_follower.rb
class DomainFollower < ActiveRecord::Base
  attr_accessible :follows, :follower

  belongs_to :follower, :class_name => "User", :foreign_key => "follower", :primary_key => "id"
  has_one :domain, :class_name => "Domain", :foreign_key => "id", :primary_key => "id"

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :email, :handle, :password, :password_salt

  validates_uniqueness_of :handle
  validates_presence_of :handle, :password, :email
  validates_size_of :handle, :within => 1..20
  validates_size_of :password, :within => 1..100
  validates_format_of :email,
    :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i
  validates_format_of :handle, :with => /^\w+$/i,
   :message => "can only contain letters and numbers."

  has_many :domains
  has_many :followers, :class_name => 'UserFollower', :foreign_key => "follows" 

  def build_params
    begin
      self.password_salt = build_salt
      self.password = build_password(password, password_salt)
    rescue
      return false
    end
    return true
  end

  def build_password(password, salt)
    Digest::MD5.hexdigest(password + salt)
  end

  def build_salt
    o =  [('a'..'z'),('A'..'Z'),(0..9)].map{|i| i.to_a}.flatten
    string  =  (0...10).map{ o[rand(o.length)] }.join
  end

  def authenticate(real_password, guess_password, password_salt)
    if real_password == build_password(guess_password, password_salt)
      true
    else
      false
    end
  end

end

app/models/user_follower.rb
class UserFollower < ActiveRecord::Base
  attr_accessible :follows, :follower
  belongs_to :follower, :class_name => "User2", :foreign_key => "follower", :primary_key => "id"
  belongs_to :follows, :class_name => "User", :foreign_key => "follows", :primary_key => "id"
  has_many :domains, :class_name => "Domain", :foreign_key => "user_id", :primary_key => "follower"
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def signout
    reset_session
    redirect_to root_path()
  end

  def signup
    @user = User.new
    # if post
    if request.post?
      # toss domains in session
      session[:domains] = params[:domains]
    end
  end

  def signin
    if request.post?
      email = params[:email]
      password = params[:password]
      user = User.find_by_email(email)
      if user && user.authenticate(user.password, password, user.password_salt) 
        session[:user_id] = user.id
        session[:username] = user.handle
        redirect_to domains_path()
      else
        redirect_to signin_path(), :flash => { :error => "Invalid email or password" }
      end
    end 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
   
  def index
    @new_domains_ids = add_domains()
    @domains = Domain.where(:user_id => session[:user_id])
    @friends = UserFollower.includes(:follows, :follows => :domains).where('follower = ?', session[:user_id])
  end

  def show
    @domain = Domain.includes(:user).find(params[:id])
    @followers = DomainFollower.where(:follows => @domain.id)
    if @domain && session[:user_id]
      if @domain.user.id == session[:user_id]
        @is_owner = true
      else
        @is_owner = false
      end
    else
      @is_owner = false
    end

  end

  def follow
    follow_id = params[:id]

    unless DomainFollower.where(:follows => follow_id).where(:follower => session[:user_id]).empty?
      # Should then unfollow
      DomainFollower.where(:follower => session[:user_id]).where(:follows => follow_id).destroy_all
      render :json => true
      return 
    end

    if DomainFollower.create(:follower => session[:user_id], :follows => follow_id)
      render :json => true
    else
      render :json => false
    end
  end


  def add_domains 
    domains = split_domains
    new_domain_ids = []
    unless domains.blank? || domains == false
      domains.each do |domain|
        domain = Domainatrix.parse(domain)
        domain = domain.domain + "." + domain.public_suffix
        if Domain.where(:name => domain, :user_id => session[:user_id]).empty?
          new_domain = Domain.create(:user_id => session[:user_id], :name => domain, :confirmed => false)
          new_domain_ids.push(new_domain.id)
        end
      end
    end
  end

  def split_domains
    if session[:domains] 
      domains = session[:domains]
    elsif params[:domains]
      domains = params[:domains]
    end
    if domains 
      domains_array = domains.split(/[,\r\n\s]/).reject(&:empty?)
      if domains_array.count == 0 && domains.length > 0
        domains_array = []
        domains_array.push(domains)
      end
      return domains_array
    else
      return false
    end
  end

  def new
    
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.find(session[:user_id])
    @domains = @user.domains
    @domains_following = DomainFollower.includes(:domain, :domain => :user).where(:follower => @user.id)
  end
  def follow
    follow_id = params[:id]

    unless follow_id.to_i == session[:user_id].to_i
      # User already follows
      unless UserFollower.where(:follower => session[:user_id]).where(:follows => follow_id).empty?
        # Should then unfollow
        UserFollower.where(:follower => session[:user_id]).where(:follows => follow_id).destroy_all
        render :json => true 
        return 
      end

      @follower = UserFollower.new
      @follower.follower = User.find(session[:user_id])
      @follower.follows = follow_id
      if @follower.save
        render :json => true
      else
        render :json => false
      end
    end
  end

  def show 
    @user = User.find(params[:id])
    @domains = @user.domains
    @followers = @user.followers
  end

  def create
    @user = params[:user]
    @newuser = User.new(@user)
    @newuser.build_params
    if @newuser.build_params && @newuser.save
      session[:user_id] = @newuser.id
      session[:username] = @newuser.handle
      redirect_to domains_path()
    else 
      flash[:error] = @newuser.errors
      redirect_to signup_path()
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/accounts/signin.html.erb
<%=form_for signin_path :via => "POST" do |f|%>
<div class="box_container navbar-inner main_box">
  <div class="box navbar">
    <div class="box_title brand">
      Login to your account
    </div>
    <div class="box_body brand">
      <%=f.label :email %>
      <%=f.text_field :email, :name => :email%>
      <%=f.label :password %>
      <%=f.password_field :password , :name => :password%>
    </div>
    <div class="clearfix"></div>
    <div class="box_footer">
      <%= f.submit "Login!", :class=>"btn btn-primary"%>
    </div>
  </div>
</div>
<% end %>

app/views/accounts/signup.html.erb
<%=form_for @user do |f|%>
<div class="box_container navbar-inner main_box">
  <div class="box navbar">
    <div class="box_title brand">
      Create a new account
    </div>
    <div class="box_body brand">
      <%=f.label "First name"%>
      <%=f.text_field :first_name%>
      <%=f.label "Last name"%>
      <%=f.text_field :last_name%>
      <%=f.label "Email"%>
      <%=f.text_field :email%>
      <%=f.label "Username"%>
      <%=f.text_field :handle%>
      <%=f.label "Password"%>
      <%=f.password_field :password%>
    </div>
    <div class="box_footer">
      <%= f.submit "Create your awesome account!", :class=>"btn btn-primary"%>
    </div>
  </div>
</div>
<% end %>

app/views/domains/index.html.erb
<div class="container">

<h1>Your domains <span class="header_links">
  <%=link_to new_domain_path(), :class => ["btn btn-primary"] do %>
    Add a domain
  <% end %>  
  </span>
</h1>
  <% unless @domains.count > 0 %>
    <div class="alert alert-critical">You have no domains. Register and verify a domain</div>
  <% else %>
    <%=render 'shared/listdomains'%>
  <% end %>

  <h1>Friends Domains</h1>
  <% unless @friends %>
    <div class="alert alert-critical">Start following some friends to discover great domains in your network.</div>
  <% else %>
    <table id="domains">
      <th>
        <tr>
        <td>User</td><td>Name</td><td>Confirmed</td><td>Public</td><td>Available</td><td>Price</td>
        </tr>
      </th>
      <tbody>
        <% @friends.each do |flwr| %>
          <% flwr.follows.domains.each do |dom| %>
          <tr>
            <td><%=link_to user_path(flwr.follows.id) do %><%=flwr.follows.handle%><% end %></td>
            <td><%=link_to domain_path(dom.id) do %><%=dom.name%><% end %></td>
            <td><%=dom.confirmed%></td>  
            <td><%=dom.public%></td>
            <td><%=dom.for_sell%></td>
            <td><%=dom.price%></td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/domains/new.html.erb
<div class="container">
  <% # breaking restful standards! %>
  <%=form_for "nada", :url => domains_path() do |f| %>
    <%= render 'shared/add_domain', :f => f %>
  <% end %>
</div>

app/views/domains/show.html.erb
<div class="container">
  <input type="hidden" id="follow_id" value="<%=@domain.id%>">
  <h1><%=@domain.name%></h1>

  <% if session[:user_id] %>
    <% @does_follow = @followers.select { |f| f.follower == session[:user_id] }.count  %>
    <% if @does_follow > 0 %>
      <% @follows = true %>
    <% else %>
      <% @follows = false %>
    <% end %>
  <% end %>

  <% unless @is_owner %>
    <% if @follows == true %>
      <button class="domain_follow btn btn-primary"><i class="icon-plus"></i> <span class="flw_txt"> unfollow</span></button>
    <% else %>
      <button class="domain_follow btn"><i class="icon-plus"></i> <span class="flw_txt">follow</span></button>
    <% end %>
  <% end %>
  
  <div class="domain_labels">
    <% if @domain.confirmed == true %>
    <span class="label label-success">Confirmed</span>
    <% else %>
    <span class="label label-important">Unconfirmed</span>
      <% if @is_owner %>
        <a href="#">Confirm</a>
      <% end %>
    <% end %>

    <% if @domain.for_sell == true %>
    <span class="label label-success">Available</span>
    <% else %>
    <span class="label label-important">Unavailable</span>
    <% end %>

  </div><!-- domain_labels  -->

  <%=render 'shared/followers'%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Nametag" %></title>

    <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-38591930-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>


    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%#= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>
    <%=render 'shared/menu'%>    
    <div class="container main">
        <div class="row">
          <div class="span12">

<% if flash %>
  <section id="flash">
    <% flash.each do |key, value| %>
      <div class="alert alert-error">
      <% unless value.instance_of?(String) %>
        <%=value.messages.flatten.join(" ") %>
      <% else %>
        <%=value%>
      <% end %>
      </div>
    <% end %>
  </section>
<% end %>
            <%= yield %>
          </div>
        </div><!--/row-->

        <%=render 'shared/footer'%>
    </div> <!-- /container -->
    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/shared/_add_domain.html.erb
<div class="box_container navbar-inner main_box">
  <div class="box navbar">
    <div class="box_title brand">
      Enter the domains you own here<br><span style="font-size: 10pt;">(comma or newline seperated)</span>
    </div>
    <div class="box_body">
      <textarea name="domains"></textarea>
    </div>
    <div class="box_footer">
      <% if controller.controller_name == "domains" %>
        <%=f.submit "Add these domains", :class => "btn btn-primary"%>
      <% else %>
        <%=f.submit "Signup", :class => "btn btn-primary"%>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_domains_following.html.erb
<h1>Domains you're following</h1>
  <table id="domains">
    <th>
      <tr>
      <td>Name</td><td>Confirmed</td><td>Public</td><td>Available</td><td>Price</td>
      </tr>
    </th>
    <tbody>
      <% @domains_following.each do |dom| %>
        <% dom = dom.domain %>
        <tr>
          <td><%= link_to domain_path(dom.id) do %><%=dom.name%><% end %></td>
          <td><%=dom.confirmed%></td>  
          <td><%=dom.public%></td>
          <td><%=dom.for_sell%></td>
          <td><%=dom.price%></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/shared/_followers.html.erb
<div class="followers">
  <h2>Followers</h2>
  <% @followers.each do |f| %>  
    <div class="follower">
      <div class="name">
        <%=link_to user_path(f.follower.id) do %>
        <%=f.follower.handle%>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
      <!--footer>
        <p>&copy; Company 2012</p>
      </footer-->
    <% if Rails.env.development? # only show the footer if you're in dev mode
      %>
      <footer class="row">
         <div class="twelvecol pushed last">
          <div style="color:red">Params</div>
          <%= debug(params) -%>
          <br>
        </div>
      </footer>
    <% end %>

app/views/shared/_listdomains.html.erb
  <table id="domains">
    <th>
      <tr>
      <td>Name</td><td>Confirmed</td><td>Public</td><td>Available</td><td>Price</td>
      </tr>
    </th>
    <tbody>
      <% @domains.each do |dom| %>
        <% if @new_domain_ids && @new_domain_ids.include?(dom.id) %>
          <tr class="new">
        <% else %>
          <tr>
        <% end %>
          <td><%= link_to domain_path(dom.id) do %><%=dom.name%><% end %></td>
          <td><%=dom.confirmed%></td>  
          <td><%=dom.public%></td>
          <td><%=dom.for_sell%></td>
          <td><%=dom.price%></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/shared/_menu.html.erb
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand logo" href="/">Nametag</a> <div class="brand motto">&#183; Social Domains</div>
          <div class="nav-collapse pull-right">
            <ul class="nav">
              <% if session[:user_id].blank? %>
              <li><%= link_to "Signup", signup_path()  %></li>
              <li><%= link_to "Signin", signin_path()  %></li>
              <% else %>
              <li><%= link_to session[:username], users_path() %></li>
              <li><%= link_to "Domains", domains_path() %></li>
              <li><%= link_to "Profile", users_path() %></li>
              <li><%= link_to "Signout", signout_path() %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

app/views/shared/_sidebar.html.erb
          <div class="span3"-->
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<div class="container">
  <input type="hidden" id="follow_id" value="<%=@user.id%>">
  <h1>Your domains</h1>
  <%=render 'shared/listdomains' %> 
  <%=render 'shared/domains_following' %>
</div>

app/views/users/show.html.erb
<div class="container">
  <input type="hidden" id="follow_id" value="<%=@user.id%>">
  <h1><%=@user.handle%>'s domains</h1>
  
  <% if session[:user_id] %>
    <% @does_follow = @followers.select { |f| f.follower == session[:user_id] }.count  %>
    <% if @does_follow > 0 %>
      <% @follows = true %>
    <% else %>
      <% @follows = false %>
    <% end %>
  <% end %>

  <% if session[:user_id] %>
    <% unless @user.id == session[:user_id] %>
        <% if @follows == true %>
          <button class="user_follow btn btn-primary"><i class="icon-plus"></i> <span class="flw_txt"> unfollow</span></button>
        <% else %>
          <button class="user_follow btn"><i class="icon-plus"></i> <span class="flw_txt">follow</span></button>
        <% end %>
    <% end %>
  <% end %>
  <!-- show followers -->
  <%=render 'shared/listdomains' %> 
</div>

app/views/welcome/index.html.erb
<div class="hero">
  <div class="message">
    Find, trade, sell, and register domains with friends.
  </div>
  <div class="splash"><img src="/assets/domainguy.png"></div>
</div>

<%=form_for "nada", :url => signup_path() do |f| %>
  <%= render 'shared/add_domain', :f => f %>
<% end %>
<div class="box_container_footnote">
  <%=link_to signup_path() do %>
    If you don't own a domain, click here to signup</a>
  <% end %>
</div>